asset_id_hcspots:
  default: hcspots
  type: str
asset_id_mat:
  default: mat
  type: str
asset_id_ua:
  default: ua
  type: str
band_hotspot:
  default: 2
  type: int
hcspots:
  default: null
  type: Directory
material_labels:
  default: null
  type: Directory
material_legend:
  default: asphalt,concrete,terracotta,vegetation,metal
  type: str
material_ndv:
  default: 0
  type: int
savename:
  default: hw_combined_sepolia.gpkg
  type: str
urban_atlas:
  default: null
  type: Directory
